# Generated by Django 4.0.4 on 2022-04-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('codAgregados', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'db_agregado',
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('codCafe', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'db_cafe',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('codCargo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_cargo',
            },
        ),
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('imgCatalogo', models.ImageField(default='null', upload_to='fotosPostres')),
            ],
            options={
                'db_table': 'db_catalogo',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('cod_comuna', models.CharField(default='', max_length=10)),
                ('nombre', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'db_comuna',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('codFormaPago', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'db_formapago',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('precio', models.CharField(default='', max_length=20)),
                ('stock', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='null', upload_to='fotosPostres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'db_postres',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('cod_region', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_region',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clave', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'db_registro',
            },
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('codTamano', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tamano',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_suc', models.AutoField(primary_key=True, serialize=False)),
                ('cod_sucursal', models.CharField(max_length=10)),
                ('direccion', models.TextField(default=0)),
                ('id_comuna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.comuna')),
            ],
            options={
                'db_table': 'db_sucursal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.region')),
            ],
            options={
                'db_table': 'db_provincia',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('papellido', models.CharField(max_length=20)),
                ('sapellido', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.comuna')),
            ],
            options={
                'db_table': 'db_persona',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateField(verbose_name='Fecha de compra')),
                ('descripcion', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=200)),
                ('codFormaPago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='administrador.formapago')),
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='administrador.persona')),
            ],
            options={
                'db_table': 'db_pedido',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.CharField(max_length=200)),
                ('cargo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.cargo')),
                ('rut_persona', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.persona')),
                ('sucursal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.sucursal')),
            ],
            options={
                'db_table': 'db_empleado',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.provincia'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.poll')),
            ],
        ),
        migrations.CreateModel(
            name='CafeTam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=50)),
                ('codTamano', models.CharField(max_length=40)),
                ('codCafe', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='administrador.cafe')),
            ],
            options={
                'db_table': 'db_cafetam',
            },
        ),
    ]
